Repository AY2324S2-CS2103T-F14-1/tp, pull requests merged in 2024-03, with the labels that each got.

#33 Edit AboutUs.md making sure CI banners pointing to own project
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/minghowc.png
  docs/team/ashley.md
Labels: documentation

#48 Update edit test cases
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: bug

#67 Fix tag feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Tag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ViewPanel.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: enhancement

#70 Fix test cases bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Tag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ViewPanel.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug

#72 Reminder Command, Updated user guide with the suggestions
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ReminderCommandParser.java
  src/main/java/seedu/address/model/person/InterviewDate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
Labels: enhancement

#85 DG updated to include implementation of NoteCommand
  docs/DeveloperGuide.md
  docs/diagrams/NoteCommandClassDiagram.puml
  docs/diagrams/NoteSequenceDiagram.puml
Labels: documentation

#90 Update UG with new layout
  docs/UserGuide.md
  docs/images/quickstart/java-installation.png
  src/main/java/seedu/internhub/model/person/InterviewDate.java
  src/main/java/seedu/internhub/model/person/Person.java
  src/test/java/seedu/internhub/logic/commands/ReminderCommandTest.java
Labels: documentation
