Repository AY2324S2-CS2103T-F14-1/tp, pull requests merged in 2024-04, with the labels that each got.

#91 Updated User Interface, Fixed Bugs and EditCommand Documentation
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandClassDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  src/main/java/seedu/internhub/model/person/InterviewDate.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/OldDarkTheme.css
  src/test/java/seedu/internhub/logic/commands/ReminderCommandTest.java
Labels: bug, user interface

#97 UG update + Ui fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/GUI_annotation.png
  docs/images/Ui_new.png
  docs/images/note-feature/note_1.png
  docs/images/note-feature/note_2.png
  docs/images/note-feature/note_3.png
  docs/images/note-feature/note_4.png
  src/main/resources/view/ViewPanel.fxml
Labels: bug, documentation

#98 UG Layout change
  docs/UserGuide.md
  docs/diagrams/NoteCommandClassDiagram.puml
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: documentation

#103 Filter changed syntax + UG updated for Note with new GUI
  docs/UserGuide.md
  docs/images/UserGuide/GUI_annotation.png
  docs/images/UserGuide/Ui.png
  docs/images/note-feature/note_4.png
  src/main/java/seedu/internhub/logic/commands/FilterCommand.java
  src/main/java/seedu/internhub/logic/parser/FilterCommandParser.java
  src/test/java/seedu/internhub/logic/parser/FilterCommandParserTest.java
Labels: documentation, enhancement

#105 Filter, View UG, info box style update
  docs/UserGuide.md
  docs/images/filter/filterIResult.png
  docs/images/find/findBurgerResult.png
  docs/images/view/view3Result.png
  src/main/resources/view/ViewPanel.fxml
Labels: documentation

#110 UG printable with section breaks
  docs/UserGuide.md
Labels: documentation

#111 Update UserGuide.md for FAQ
  docs/UserGuide.md
Labels: documentation

#112 Refactor Ui.png
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#113 Update DeveloperGuide.md with 3 test cases for Saving Data
  docs/DeveloperGuide.md
Labels: documentation

#188 Ug fix 1
  docs/UserGuide.md
  docs/images/UserGuide/addCommandExample1.png
  docs/images/UserGuide/addCommandExample2.png
  docs/images/UserGuide/deleteCommandAfter.png
  docs/images/UserGuide/deleteCommandBefore.png
  docs/images/UserGuide/deleteExample.png
  docs/images/UserGuide/edit_example.png
  docs/images/UserGuide/list.png
  docs/images/filter/filterIResult.png
  docs/images/find/findBurgerResult.png
  docs/images/view/view1Result.png
Labels: documentation

#189 update UG to fix bugs
  docs/UserGuide.md
  src/main/java/seedu/internhub/logic/Messages.java
  src/main/java/seedu/internhub/logic/commands/AddCommand.java
  src/main/java/seedu/internhub/logic/commands/ClearCommand.java
  src/main/java/seedu/internhub/logic/commands/DeleteCommand.java
  src/main/java/seedu/internhub/logic/commands/EditCommand.java
  src/main/java/seedu/internhub/logic/commands/ExitCommand.java
  src/main/java/seedu/internhub/logic/commands/ListCommand.java
  src/main/java/seedu/internhub/logic/commands/NoteCommand.java
  src/main/java/seedu/internhub/logic/commands/ViewCommand.java
  src/main/java/seedu/internhub/logic/parser/EditCommandParser.java
  src/test/java/seedu/internhub/logic/commands/ViewCommandTest.java
Labels: bug, documentation

#201 Note activity diagram DG
  docs/DeveloperGuide.md
  docs/diagrams/NoteActivityDiagram.puml
  docs/diagrams/NoteCommandClassDiagram.puml
  docs/team/jawad.md
Labels: documentation

#202 Bug fix for filter command failing with inputs
  src/main/java/seedu/internhub/model/person/Tag.java
Labels: bug

#205 Dg 1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewActivityDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
Labels: documentation

#214 UG and DG updates
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/AddCommandClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: documentation

#218 Use case update, Effort section
  docs/DeveloperGuide.md
Labels: documentation

#224 FAQ update
  docs/UserGuide.md
Labels: documentation
